name: "Publish images"
on:
  pull_request:
    branches: [latest]
  push:
    branches: [latest]

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: cache nix store
        id: cache-nix
        uses: actions/cache@v2
        with:
          path: |
            ~/.nix-portable/store
            ~/bin/nix
          key: nix-${{ hashFiles('shell.nix') }}-${{ hashFiles('nix/**') }}

      - name: install nix-portable
        if: steps.cache-nix.outputs.cache-hit != 'true'
        run: |
          mkdir ~/bin
          wget -qO ~/bin/nix-portable https://github.com/DavHau/nix-portable/releases/download/v003/nix-portable
          chmod +x ~/bin/nix-portable

      - name: Generate figures
        run: ~/bin/nix-portable nix-shell --command "snakemake -j1"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: data/plots/
